// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"net/http"
)

// CloseADeployRequestRequestBodyStateEnum - The deploy request will be updated to this state
type CloseADeployRequestRequestBodyStateEnum string

const (
	CloseADeployRequestRequestBodyStateEnumClosed CloseADeployRequestRequestBodyStateEnum = "closed"
)

func (e *CloseADeployRequestRequestBodyStateEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "closed":
		*e = CloseADeployRequestRequestBodyStateEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for CloseADeployRequestRequestBodyStateEnum: %s", s)
	}
}

type CloseADeployRequestRequestBody struct {
	// The deploy request will be updated to this state
	State *CloseADeployRequestRequestBodyStateEnum `json:"state,omitempty"`
}

type CloseADeployRequestRequest struct {
	RequestBody *CloseADeployRequestRequestBody `request:"mediaType=application/json"`
	// The name of the deploy request's database
	Database string `pathParam:"style=simple,explode=false,name=database"`
	// The number of the deploy request
	Number string `pathParam:"style=simple,explode=false,name=number"`
	// The name of the deploy request's organization
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
}

type CloseADeployRequestResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Returns the updated deploy request
	CloseADeployRequest200ApplicationJSONObject map[string]map[string]interface{}
}
