// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type CompleteAnErroredDeployRequest struct {
	// The name of the deploy request's database
	Database string `pathParam:"style=simple,explode=false,name=database"`
	// The number of the deploy request
	Number string `pathParam:"style=simple,explode=false,name=number"`
	// The name of the deploy request's organization
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
}

type CompleteAnErroredDeploy200ApplicationJSON struct {
}

type CompleteAnErroredDeployResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Returns the completed deploy request
	CompleteAnErroredDeploy200ApplicationJSONObject map[string]CompleteAnErroredDeploy200ApplicationJSON
}
