// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type CompleteARevertRequest struct {
	// The name of the deploy request's database
	Database string `pathParam:"style=simple,explode=false,name=database"`
	// The number of the deploy request
	Number string `pathParam:"style=simple,explode=false,name=number"`
	// The name of the deploy request's organization
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
}

type CompleteARevert200ApplicationJSON struct {
}

type CompleteARevertResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Returns the deploy request that was reverted
	CompleteARevert200ApplicationJSONObject map[string]CompleteARevert200ApplicationJSON
}
