// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type CreateABranchRequestBody struct {
	// If provided, restores the backup's schema and data to the new branch
	BackupID *string `json:"backup_id,omitempty"`
	// The name of the branch
	Name string `json:"name"`
	// Parent branch
	ParentBranch string `json:"parent_branch"`
}

type CreateABranchRequest struct {
	// The name of the database the branch belongs to
	Database string `pathParam:"style=simple,explode=false,name=database"`
	// The name of the organization the branch belongs to
	Organization string                    `pathParam:"style=simple,explode=false,name=organization"`
	RequestBody  *CreateABranchRequestBody `request:"mediaType=application/json"`
}

type CreateABranch201ApplicationJSON struct {
}

type CreateABranchResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Returns the created branch
	CreateABranch201ApplicationJSONObject map[string]CreateABranch201ApplicationJSON
}
