// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type CreateADatabaseRequestBody struct {
	// The name of the database
	Name string `json:"name"`
	// Notes about the database
	Notes *string `json:"notes,omitempty"`
}

type CreateADatabaseRequest struct {
	// The name of the organization the database belongs to
	Organization string                      `pathParam:"style=simple,explode=false,name=organization"`
	RequestBody  *CreateADatabaseRequestBody `request:"mediaType=application/json"`
}

type CreateADatabase201ApplicationJSON struct {
}

type CreateADatabaseResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Returns the created database
	CreateADatabase201ApplicationJSONObject map[string]CreateADatabase201ApplicationJSON
}
