// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type CreateADeployRequestRequestBody struct {
	// The name of the branch the deploy request is created from
	Branch *string `json:"branch,omitempty"`
	// The name of the branch the deploy request will be merged into
	IntoBranch *string `json:"into_branch,omitempty"`
	// Notes about the deploy request
	Notes *string `json:"notes,omitempty"`
	// The number of the deploy request
	Number *string `json:"number,omitempty"`
}

type CreateADeployRequestRequest struct {
	// The name of the deploy request's database
	Database string `pathParam:"style=simple,explode=false,name=database"`
	// The name of the deploy request's organization
	Organization string                           `pathParam:"style=simple,explode=false,name=organization"`
	RequestBody  *CreateADeployRequestRequestBody `request:"mediaType=application/json"`
}

type CreateADeployRequestResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Returns the created deploy request
	CreateADeployRequest200ApplicationJSONObject map[string]map[string]interface{}
}
