// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteAnOauthTokenRequest struct {
	// The ID of the OAuth application
	ApplicationID string `pathParam:"style=simple,explode=false,name=application_id"`
	// The name of the organization the OAuth application belongs to
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The ID of the OAuth application token
	TokenID string `pathParam:"style=simple,explode=false,name=token_id"`
}

type DeleteAnOauthTokenResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
