// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteABranchPasswordRequest struct {
	// The name of the branch the password belongs to
	Branch string `pathParam:"style=simple,explode=false,name=branch"`
	// The name of the database the password belongs to
	Database string `pathParam:"style=simple,explode=false,name=database"`
	// The ID of the password
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// The name of the organization the password belongs to
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
}

type DeleteABranchPasswordResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
