// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DemoteABranchRequest struct {
	Database     float64 `pathParam:"style=simple,explode=false,name=database"`
	Name         float64 `pathParam:"style=simple,explode=false,name=name"`
	Organization float64 `pathParam:"style=simple,explode=false,name=organization"`
}

type DemoteABranchResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Demotes a branch from production to development
	DemoteABranch200ApplicationJSONObject map[string]map[string]interface{}
}
