// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetAnOrganizationRequest struct {
	// The name of the organization
	Name string `pathParam:"style=simple,explode=false,name=name"`
}

type GetAnOrganizationResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Returns an organization
	GetAnOrganization200ApplicationJSONObject map[string]map[string]interface{}
}
