// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetADeployQueueRequest struct {
	// The name of the deploy request's database
	Database string `pathParam:"style=simple,explode=false,name=database"`
	// The name of the deploy request's organization
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
}

type GetADeployQueueResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Returns the deploy queue for a database
	GetADeployQueue200ApplicationJSONObject map[string]map[string]interface{}
}
