// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetAnOauthTokenRequest struct {
	// The ID of the OAuth application
	ApplicationID string `pathParam:"style=simple,explode=false,name=application_id"`
	// The name of the organization the OAuth application belongs to
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// The ID of the OAuth application token
	TokenID string `pathParam:"style=simple,explode=false,name=token_id"`
}

type GetAnOauthToken200ApplicationJSON struct {
}

type GetAnOauthTokenResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Returns an OAuth token that was issued on behalf of the OAuth application
	GetAnOauthToken200ApplicationJSONObject map[string]GetAnOauthToken200ApplicationJSON
}
