// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetADemotionRequestRequest struct {
	// The name of the database the branch belongs to
	Database string `pathParam:"style=simple,explode=false,name=database"`
	// The name of the branch
	Name string `pathParam:"style=simple,explode=false,name=name"`
	// The name of the organization the branch belongs to
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
}

type GetADemotionRequest200ApplicationJSON struct {
}

type GetADemotionRequestResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Returns the branch demotion request
	GetADemotionRequest200ApplicationJSONObject map[string]GetADemotionRequest200ApplicationJSON
}
