// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetADeploymentRequest struct {
	// The name of the deploy request's database
	Database string `pathParam:"style=simple,explode=false,name=database"`
	// The number of the deploy request
	Number string `pathParam:"style=simple,explode=false,name=number"`
	// The name of the deploy request's organization
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
}

type GetADeployment200ApplicationJSON struct {
}

type GetADeploymentResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Returns the deployment for a deploy request
	GetADeployment200ApplicationJSONObject map[string]GetADeployment200ApplicationJSON
}
