// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetAnOauthApplicationRequest struct {
	// The ID of the OAuth application
	ApplicationID string `pathParam:"style=simple,explode=false,name=application_id"`
	// The name of the organization the OAuth application belongs to
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
}

type GetAnOauthApplication200ApplicationJSON struct {
}

type GetAnOauthApplicationResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Returns information abuot an OAuth application
	GetAnOauthApplication200ApplicationJSONObject map[string]GetAnOauthApplication200ApplicationJSON
}
