// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetADatabaseRequest struct {
	// The name of the database
	Name string `pathParam:"style=simple,explode=false,name=name"`
	// The name of the organization the database belongs to
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
}

type GetADatabaseResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Returns a database
	GetADatabase200ApplicationJSONObject map[string]map[string]interface{}
}
