// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetBranchStatusRequest struct {
	// The name of the database the branch belongs to
	Database string `pathParam:"style=simple,explode=false,name=database"`
	// The name of the branch
	Name string `pathParam:"style=simple,explode=false,name=name"`
	// The name of the organization the branch belongs to
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
}

type GetBranchStatus200ApplicationJSON struct {
}

type GetBranchStatusResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Returns the branch status
	GetBranchStatus200ApplicationJSONObject map[string]GetBranchStatus200ApplicationJSON
}
