// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type ListOauthTokensRequest struct {
	// The ID of the OAuth application
	ApplicationID string `pathParam:"style=simple,explode=false,name=application_id"`
	// The name of the organization the OAuth application belongs to
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// If provided, specifies the page offset of returned results
	Page *float64 `queryParam:"style=form,explode=true,name=page"`
	// If provided, specifies the number of returned results
	PerPage *float64 `queryParam:"style=form,explode=true,name=per_page"`
}

type ListOauthTokensResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Returns a list of OAuth tokens issued on behalf of the OAuth application
	ListOauthTokens200ApplicationJSONObject map[string]map[string]interface{}
}
