// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type ListDatabaseRegionsRequest struct {
	// The name of the database
	Name string `pathParam:"style=simple,explode=false,name=name"`
	// The name of the organization the database belongs to
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// If provided, specifies the page offset of returned results
	Page *float64 `queryParam:"style=form,explode=true,name=page"`
	// If provided, specifies the number of returned results
	PerPage *float64 `queryParam:"style=form,explode=true,name=per_page"`
}

type ListDatabaseRegions200ApplicationJSON struct {
}

type ListDatabaseRegionsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Returns the available regions for a database
	ListDatabaseRegions200ApplicationJSONObject map[string]ListDatabaseRegions200ApplicationJSON
}
