// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type ListDeployOperationsRequest struct {
	// The name of the database the deploy request belongs to
	Database string `pathParam:"style=simple,explode=false,name=database"`
	// The number of the deploy request
	Number string `pathParam:"style=simple,explode=false,name=number"`
	// The name of the organization the deploy request belongs to
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// If provided, specifies the page offset of returned results
	Page *float64 `queryParam:"style=form,explode=true,name=page"`
	// If provided, specifies the number of returned results
	PerPage *float64 `queryParam:"style=form,explode=true,name=per_page"`
}

type ListDeployOperations200ApplicationJSON struct {
}

type ListDeployOperationsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Returns a list of deploy operations for the deploy request
	ListDeployOperations200ApplicationJSONObject map[string]ListDeployOperations200ApplicationJSON
}
