// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type ListRegionsForAnOrganizationRequest struct {
	// The name of the organization
	Name string `pathParam:"style=simple,explode=false,name=name"`
	// If provided, specifies the page offset of returned results
	Page *float64 `queryParam:"style=form,explode=true,name=page"`
	// If provided, specifies the number of returned results
	PerPage *float64 `queryParam:"style=form,explode=true,name=per_page"`
}

type ListRegionsForAnOrganizationResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Returns the organization's regions
	ListRegionsForAnOrganization200ApplicationJSONObject map[string]map[string]interface{}
}
