// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type ListReadOnlyRegionsRequest struct {
	// The name of the database
	Name string `pathParam:"style=simple,explode=false,name=name"`
	// The name of the organization the database belongs to
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
	// If provided, specifies the page offset of returned results
	Page *float64 `queryParam:"style=form,explode=true,name=page"`
	// If provided, specifies the number of returned results
	PerPage *float64 `queryParam:"style=form,explode=true,name=per_page"`
}

type ListReadOnlyRegions200ApplicationJSON struct {
}

type ListReadOnlyRegionsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// List of the database's read-only regions
	ListReadOnlyRegions200ApplicationJSONObject map[string]ListReadOnlyRegions200ApplicationJSON
}
