// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type QueueADeployRequestRequest struct {
	// The name of the database the deploy request belongs to
	Database string `pathParam:"style=simple,explode=false,name=database"`
	// The number of the deploy request
	Number string `pathParam:"style=simple,explode=false,name=number"`
	// The name of the organization the deploy request belongs to
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
}

type QueueADeployRequest200ApplicationJSON struct {
}

type QueueADeployRequestResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Returns the deployed deploy request
	QueueADeployRequest200ApplicationJSONObject map[string]QueueADeployRequest200ApplicationJSON
}
