// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type UpdateAutoApplyForDeployRequestRequest struct {
	// The name of the deploy request's database
	Database string `pathParam:"style=simple,explode=false,name=database"`
	// The number of the deploy request
	Number string `pathParam:"style=simple,explode=false,name=number"`
	// The name of the deploy request's organization
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
}

type UpdateAutoApplyForDeployRequest200ApplicationJSON struct {
}

type UpdateAutoApplyForDeployRequestResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Returns the deploy request whose auto-apply setting was updated
	UpdateAutoApplyForDeployRequest200ApplicationJSONObject map[string]UpdateAutoApplyForDeployRequest200ApplicationJSON
}
