// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type UpdateABranchPasswordRequestBody struct {
	// The display name for the password
	DisplayName string `json:"display_name"`
	// A read-only region of the database branch. If present, the password results will be filtered to only those in the region
	ReadOnlyRegionID *string `json:"read_only_region_id,omitempty"`
}

type UpdateABranchPasswordRequest struct {
	RequestBody *UpdateABranchPasswordRequestBody `request:"mediaType=application/json"`
	// The name of the branch the password belongs to
	Branch string `pathParam:"style=simple,explode=false,name=branch"`
	// The name of the database the password belongs to
	Database string `pathParam:"style=simple,explode=false,name=database"`
	// The ID of the password
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// The name of the organization the password belongs to
	Organization string `pathParam:"style=simple,explode=false,name=organization"`
}

type UpdateABranchPasswordResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Updates a database branch password
	UpdateABranchPassword200ApplicationJSONObject map[string]map[string]interface{}
}
