// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type UpdateAnOrganizationRequestBody struct {
	// The billing email for the organization
	BillingEmail *string `json:"billing_email,omitempty"`
	// Whether or not only admins can access production
	RequireAdminForProductionAccess *bool `json:"require_admin_for_production_access,omitempty"`
}

type UpdateAnOrganizationRequest struct {
	// The name of the organization
	Name        string                           `pathParam:"style=simple,explode=false,name=name"`
	RequestBody *UpdateAnOrganizationRequestBody `request:"mediaType=application/json"`
}

type UpdateAnOrganization200ApplicationJSON struct {
}

type UpdateAnOrganizationResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Returns the updated organization
	UpdateAnOrganization200ApplicationJSONObject map[string]UpdateAnOrganization200ApplicationJSON
}
